train_rl:
    named_configs:
        - ${env.name}
    config_updates:
        common:
            log_dir: logss/

eval_rl_policy:
    named_configs:
        - ${env.name}
    config_updates:
        policy_path: logss/policies/final
        policy_type: ppo
        videos: 1

train_adversarial:
    command_name: "airl"
    named_configs:
        - ${env.name}
    config_updates:
        common:
            log_dir: logss/
        demonstrations:
            rollout_path: logss/rollouts/final.pkl

eval_irl_policy:
    named_configs:
        - ${env.name}
    config_updates:
        policy_path: logss/checkpoints/final/gen_policy
        policy_type: ppo
        videos: 1
