train_rl:
    named_configs:
        - ${env.name}
    config_updates:
        common:
            log_dir: logss/
        seed: ${seed.value}

eval_rl_policy:
    named_configs:
        - ${env.name}
    config_updates:
        policy_path: logss/policies/final
        policy_type: ppo
        videos: 1
        seed: ${seed.value}

train_adversarial:
    command_name: "airl"
    named_configs:
        - ${env.name}
    config_updates:
        common:
            log_dir: logss/
        demonstrations:
            rollout_path: /work/frtim/clean_airl_runs/${demonstrator.name}/logss/rollouts/final.pkl
        seed: ${seed.value}

eval_irl_policy:
    named_configs:
        - ${env.name}
    config_updates:
        policy_path: logss/checkpoints/final/gen_policy
        policy_type: ppo
        videos: 1
        seed: ${seed.value}
