train_rl:
    named_configs: ${run_test.train_rl.named_configs}
    config_updates:
        common:
            log_dir: logss/
        seed: ${seed.value}

eval_rl_policy:
    named_configs:
        - ${env.name}
    config_updates:
        policy_path: logss/policies/final
        policy_type: ppo
        videos: 1
        seed: ${seed.value}

train_adversarial:
    command_name: gail
    named_configs:
      - ${env.name}
      - ${learner_enc.config}
      - ${exp_enc.config}
      - ${reward_net.value}
      - common.wandb_logging
    config_updates:
        common:
            log_dir: logss/
            wandb:
                wandb_tag: ${task_name}
                wandb_name_prefix: ${task_name}
        demonstrations:
            rollout_path: ${exec.output_dir}/airl_saved/rl_demos/${dem.name}/logss/rollouts/final.pkl
        seed: ${seed.value}
        algorithm_kwargs:
            n_enc_updates_per_round: ${n_enc}
            n_disc_updates_per_round: ${n_disc}
            enc_lr: ${enc_lr}
            disc_lr: ${disc_lr}
            enc_weight_decay: ${enc_weight_decay}
            use_wgan: ${use_wgan}
            disc_opt_cls: ${disc_opt_cls}
            clip_disc_weights: ${clip_disc}


eval_irl_policy:
    named_configs:
        - ${env.name}
    config_updates:
        policy_path: logss/checkpoints/final/gen_policy
        policy_type: ppo
        videos: 1
        seed: ${seed.value}
