train_rl:
    named_configs: ${run_test.train_rl.named_configs}
    config_updates:
        common:
            log_dir: logss/
        seed: ${seed.value}

eval_rl_policy:
    named_configs:
        - ${env.name}
    config_updates:
        policy_path: /users/frtim/Code_onlyremote/rl-baselines3-zoo/logs/td3/seals/Hopper-v0_1
        policy_type: td3
        videos: 0
        seed: ${seed.value}

train_adversarial:
    command_name: gail
    named_configs:
      - ${env.name}
      - ${learner_enc.config}
      - ${exp_enc.config}
      - ${reward_net.value}
      - ${wandb.value}
    config_updates:
        common:
            log_dir: logss/
            wandb:
                wandb_tag: ${task_name}
                wandb_name_prefix: ${task_name}
        demonstrations:
            rollout_path: ${exec.output_dir}/airl_saved/rl_demos/${dem.name}/logss/rollouts/final.pkl
        seed: ${seed.value}
        rl:
            lr: ${rl_lr}
        algorithm_kwargs:
            n_gen_updates_per_round: ${n_enc}
            n_disc_updates_per_round: ${n_disc}
            n_enc_updates_per_round: ${n_enc}
            enc_lr: ${enc_lr}
            disc_lr: ${disc_lr}
            use_wgan: ${use_wgan}
            disc_opt_cls: ${disc_opt_cls}
            alt_enc_disc: ${alt_enc_disc}

eval_irl_policy:
    named_configs:
        - ${env.name}
    config_updates:
        policy_path: logss/checkpoints/final/gen_policy
        policy_type: ppo
        videos: 1
        seed: ${seed.value}
