
n_disc_updates_per_round: 16
n_enc_updates_per_round: 1
enc_lr: 1e-3
disc_lr: 1e-3

train_rl:
    named_configs: ${run_test.train_rl.named_configs}
    config_updates:
        common:
            log_dir: logss/
        seed: ${seed.value}

eval_rl_policy:
    named_configs:
        - ${env.name}
    config_updates:
        policy_path: logss/policies/final
        policy_type: ppo
        videos: 1
        seed: ${seed.value}

train_adversarial:
    command_name: gail
    named_configs:
      - ${env.name}
      - ${learner_enc.config}
      - ${exp_enc.config}
    config_updates:
        common:
            log_dir: logss/
        demonstrations:
            rollout_path: ${exec.output_dir}/airl_saved/rl_demos/${demonstrator.name}/logss/rollouts/final.pkl
        seed: ${seed.value}
        algorithm_kwargs:
            n_enc_updates_per_round: ${sacred.n_enc_updates_per_round}
            n_disc_updates_per_round: ${sacred.n_disc_updates_per_round}
            enc_lr: ${sacred.enc_lr}
            disc_lr: ${sacred.disc_lr}
            enc_weight_decay: 0.0

eval_irl_policy:
    named_configs:
        - ${env.name}
    config_updates:
        policy_path: logss/checkpoints/final/gen_policy
        policy_type: ppo
        videos: 1
        seed: ${seed.value}
