env: "hopper"
dem: "hopper"
dem_mod: 0
dem_algo: td3

debug: False

environment:
    name: seals_${env}
demonstrator:
    name: seals_${dem}
    model: ${dem_mod}

n_gen: 1
n_disc: 1000
n_enc: 1
enc_lr: 1e-3
disc_lr: 1e-3
use_wgan: False
disc_opt_cls: "adam"
alt_enc_disc: False
task_name: "gridsearch2"
#output_dir: "/work/frtim"
output_dir: "/scratch/shared/beegfs/frtim"
actor_lr_half_steps: 500000
rl_algo: td3
scale_obs: False
n_expert_trajs: -1

defaults:
    - where: "gpu"
    - wandb: "yes"
    - exp_enc: "reduced"
    - learner_enc: "reduced"
    - sacred: standard
    - override /hydra/launcher: submitit_slurm

hydra:
    launcher:
        submitit_folder: logs/multiruns/.submitit/%j
        timeout_min: 2000
        cpus_per_task: 8
        gpus_per_node: ${where.gpus_per_node}
        partition: ${where.partition}
        constraint: ${where.constraint}
        tasks_per_node: 1
        mem_gb: 15
        nodes: 1
        name: testscript
        _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
        comment: null
        exclude: gnodec1,gnodec5
        max_num_timeout: 0
        additional_parameters: {}
        array_parallelism: 100
        setup: null

    run:
        dir: ${output_dir}/airl_runs/${task_name}/${environment.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    sweep:
        dir: ${output_dir}/airl_runs/${task_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
        subdir: ${hydra.job.override_dirname}

# add job id
job_id: ${hydra.job.num}




