
defaults:
    - state_only: "yes"
    - run_test: "no"
    - use_encoder: "yes"
    - invert_states_expert: "yes"
    - irl_algo: gail
    - env: seals_mountain_car_org
    - demonstrator: seals_mountain_car_seed_one
    - sacred: standard
    - seed: one
    - exec: cluster
    - override /hydra/launcher: submitit_slurm



hydra:
    launcher:
        submitit_folder: logs/multiruns/.submitit/%j
        timeout_min: 600
        cpus_per_task: 8
        gpus_per_node: 1
        tasks_per_node: 1
        mem_gb: 24
        nodes: 1
        name: testscript
        _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
        partition: gpu
        comment: null
        exclude: gnodec1
        max_num_timeout: 0
        additional_parameters: {}
        array_parallelism: 12
        setup: null

    run:
        dir: ${exec.output_dir}/airl_runs/${env.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    sweep:
        dir: ${exec.output_dir}/airl_runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
        subdir: ${hydra.job.override_dirname}

# add job id
job_id: ${hydra.job.num}



#python run.py env=seals_hopper_trunc demonstrator=seals_hopper_seed_five,seals_hopper_seed_three  seed=one,two,three
#python -m imitation.run.run_irl env=seals_hopper_trunc demonstrator=seals_walker_seed_one sacred=test

